version: '3.7'

services:
  api:
    build: async_api
    container_name: fast_api
    environment:
      ELASTICSEARCH_HOSTS: $ELASTIC_HOST
      REDIS_HOST: $REDIS_HOST
      REDIS_PASSWORD: $REDIS_PASSWORD
    depends_on:
      - elasticsearch
      - redis
    restart: always
    ports:
      - 8000:8000

  rs-api:
    build: rs_api
    container_name: rs_api
    environment:
      POSTGRES_DB: $POSTGRES_PREDICTIONS_DB
      POSTGRES_HOST: $POSTGRES_PREDICTIONS_HOST
      POSTGRES_PORT: $POSTGRES_PREDICTIONS_PORT
      POSTGRES_USER: $POSTGRES_PREDICTIONS_USER
      POSTGRES_PASSWORD: $POSTGRES_PREDICTIONS_PASSWORD
    depends_on:
      - postgres
      - init_postgres
    restart: always
    ports:
      - 8888:8888

  rs:
    build: rs
    container_name: rs
    environment:
      POSTGRES_DATA_DB: $POSTGRES_DATA_DB
      POSTGRES_DATA_HOST: $POSTGRES_DATA_HOST
      POSTGRES_DATA_PORT: $POSTGRES_DATA_PORT
      POSTGRES_DATA_USER: $POSTGRES_DATA_USER
      POSTGRES_DATA_PASSWORD: $POSTGRES_DATA_PASSWORD
      POSTGRES_PREDICTIONS_DB: $POSTGRES_PREDICTIONS_DB
      POSTGRES_PREDICTIONS_HOST: $POSTGRES_PREDICTIONS_HOST
      POSTGRES_PREDICTIONS_PORT: $POSTGRES_PREDICTIONS_PORT
      POSTGRES_PREDICTIONS_USER: $POSTGRES_PREDICTIONS_USER
      POSTGRES_PREDICTIONS_PASSWORD: $POSTGRES_PREDICTIONS_PASSWORD
      SSL_MODE: $SSL_MODE
    restart: always
    ports:
      - 8080:8080

  rs_etl:
    build: rs_etl
    container_name: rs_etl
    restart: always
    environment:
      POSTGRES_MOVIES_DB: $POSTGRES_MOVIES_DB
      POSTGRES_MOVIES_HOST: $POSTGRES_MOVIES_HOST
      POSTGRES_MOVIES_PORT: $POSTGRES_MOVIES_PORT
      POSTGRES_MOVIES_USER: $POSTGRES_MOVIES_USER
      POSTGRES_MOVIES_PASSWORD: $POSTGRES_MOVIES_PASSWORD

      POSTGRES_UGC_DB: $POSTGRES_UGC_DB
      POSTGRES_UGC_HOST: $POSTGRES_UGC_HOST
      POSTGRES_UGC_PORT: $POSTGRES_UGC_PORT
      POSTGRES_UGC_USER: $POSTGRES_UGC_USER
      POSTGRES_UGC_PASSWORD: $POSTGRES_UGC_PASSWORD

      POSTGRES_DATA_DB: $POSTGRES_DATA_DB
      POSTGRES_DATA_HOST: $POSTGRES_DATA_HOST
      POSTGRES_DATA_PORT: $POSTGRES_DATA_PORT
      POSTGRES_DATA_USER: $POSTGRES_DATA_USER
      POSTGRES_DATA_PASSWORD: $POSTGRES_DATA_PASSWORD
      SSL_MODE: $SSL_MODE
    depends_on:
      - es_initializer
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    restart: always

  es_initializer:
    container_name: es_initializer
    build: ./elastic
    depends_on:
      - elasticsearch

  etl:
    build: etl
    container_name: etl
    environment:
      POSTGRES_DB: $POSTGRES_MOVIES_DB
      POSTGRES_HOST: $POSTGRES_MOVIES_HOST
      POSTGRES_PORT: $POSTGRES_MOVIES_PORT
      POSTGRES_USER: $POSTGRES_MOVIES_USER
      POSTGRES_PASSWORD: $POSTGRES_MOVIES_PASSWORD
      SSL_MODE: $SSL_MODE
      ELASTIC_HOST: $ELASTIC_HOST
      REDIS_HOST: $REDIS_HOST
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: always
    depends_on:
      - es_initializer
      - postgres

  redis:
    image: redis:latest
    container_name: redis_cache
    expose:
      - 6379
    depends_on:
      - elasticsearch
    restart: always

  postgres:
    image: postgres:12.1
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    expose:
      - 5432

  init_postgres:
    build: db
    container_name: init_postgres
    environment:
      POSTGRES_HOST: $POSTGRES_MOVIES_HOST
      POSTGRES_PORT: $POSTGRES_MOVIES_PORT
      POSTGRES_USER: $POSTGRES_MOVIES_USER
      POSTGRES_PASSWORD: $POSTGRES_MOVIES_PASSWORD
      POSTGRES_MOVIES_DB: $POSTGRES_MOVIES_DB
      SSL_MODE: $SSL_MODE
    depends_on:
      - postgres


volumes:
  elasticsearch_data:
  pg_data:
